sudo: false
language: node_js
node_js:
  - "6"

cache: yarn

script:
  - make travis

notifications:
  slack:
    rooms:
    - grindr:e6H9sb52TVbjXjMDPheBPES2#builds
    on_success: always
    on_failure: always
